### ISSUE TITLE
Largest wikis with the smallest editor pools (or, any wiki with an inverse relationship between wiki size and editor community)

### ISSUE THREAD

**Issue by margeigh** [prtksxna/segmentation-data#1]
**Do you want a particular visualization? Can you link from http://datavizproject.com/?**
A. Scattor plot of …

**List the variables that you'd like to see**
A. For example:
* unique devices per editor
* rank
* etc…

**Any possible correlations and insights you're looking for?**

**Additional context**

**Comment by prtksxna** [comment]
<img width="983" alt="screen shot 2018-08-30 at 7 28 26 am" src="https://user-images.githubusercontent.com/9491/44825030-4ddf1380-ac26-11e8-90f3-10dbc276f83b.png">

Updated the page with this chart. The bottom left quadrant might be of interest. 
https://prtksxna.github.io/segmentation-data/

Feel free to re-open the issue if you want something more done here 😄

**Comment by prtksxna** [comment]
Let me know if you want me to get rid of the outliers in the data (Tagalog Wikibooks, I am looking at you)
